### ISSUE TITLE
ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by ma1n** [khanu263/SunCycleWallpaper#1]
Hey, I wanted to try out this script and its throwing the following error at me:

python3 SunCycleChanger.py
Traceback (most recent call last):
  File "SunCycleChanger.py", line 152, in <module>
    if update_required(lat, lon, date):
  File "SunCycleChanger.py", line 82, in update_required
    old_lat = float(old_coor[0])
ValueError: could not convert string to float: ''

I'm not too good with the python envoirment yet so I hope this isn't a stupid question

**Comment by khanu263** [comment]
Hey, sorry for taking so long to get back to you -- I've been crazy busy lately and have been neglecting my side projects. It's hard to say exactly what's going on without more information about the way you've set things up. It looks like it's having trouble parsing the data file used to store coordinate and timing information, so that's one place to start looking (if you haven't already figured it out or moved on to something else).

Also, I'm currently in the middle of rewriting this thing from the ground up, with a much easier-to-use installation process. I hope to be deploying this soon, and there's a good chance any bugs you have will be gone since I'm basically ripping everything out and starting fresh with lessons I've learned in the last couple years. So if you're interested, be on the lookout for that!
